# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='post')),
                ('texto', models.TextField(verbose_name='descripcion')),
                ('tags', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('publicado', models.DateField()),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MysInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.ManyToManyField(related_name='interes', to='Post.Categoria')),
            ],
        ),
    ]
