# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20201024_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desactivar',
            field=models.DateField(blank=True, null=True, verbose_name='Desactivar Post'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publicado',
            field=models.DateField(verbose_name='Programar publicacion'),
        ),
    ]
