# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20201027_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='desactivar',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publicado',
            field=models.DateField(null=True, verbose_name='Programar publicacion'),
        ),
    ]
